services:
  #  bot:
  #    build: bot
  #    depends_on:
  #      - postgres
  #      - coordinator
  #      - contest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  coordinator:
    build: coordinator
    ports:
      - "5002:8000"
    depends_on:
      - llm
      - contest
    volumes:
      - ./tools:/app/tools
  
  contest:
    build: contest
    ports:
      - "5001:8000"
    depends_on:
      - llm
    volumes:
      - ./tools:/app/tools

  llm:
    build: llm
    ports:
      - "5003:8000"
    volumes:
      - ./tools:/app/tools


volumes:
  pg-data:

