"""initial

Revision ID: 72b5aac51cad
Revises:
Create Date: 2024-12-28 09:24:15.067359

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72b5aac51cad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'wizard',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('speed', sa.Integer(), nullable=False),
        sa.Column('power', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'spell',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type_', sa.Enum('ACTIVE', 'PASSIVE', name='spelltype'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('manacost', sa.Integer(), nullable=False),
        sa.Column('wizard_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['wizard_id'],
            ['wizard.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell')
    op.drop_table('wizard')
    op.drop_table('user')
    # ### end Alembic commands ###
